name: 'Branch Build'
run-name: '${{ github.workflow }} for ${{ github.ref_name }}'

on: push

permissions:
  pull-requests: read
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '6.0.x', '7.0.x' ]
    steps:
    - name: Checkout
      uses: actions/checkout@v3  

    - name: Set Up .NET ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    
    - name: Configure Dependency Cache
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-nuget-${{ matrix.dotnet-version }}
        restore-keys: |
          ${{ runner.os }}-nuget-${{ matrix.dotnet-version }}

    - name: Restore ResultCs Dependencies
      run: dotnet restore ./src/ResultCs/ResultCs.csproj

    - name: Build ResultCs
      run: dotnet build ./src/ResultCs/ResultCs.csproj

    - name: Run ResultCs Unit Tests
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput=./TestResults/lcov.info ./test/ResultCs.Tests.Unit/ResultCs.Tests.Unit.csproj

    - name: Run ResultCs Integration Tests
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput=./TestResults/lcov.info ./test/ResultCs.Tests.Integration/ResultCs.Tests.Integration.csproj

    - name: Create code coverage report
      run: |
        dotnet tool install -g dotnet-reportgenerator-globaltool
        reportgenerator -reports:${{ github.workspace }}/**/lcov.info -targetdir:${{ github.workspace }}/CodeCoverage -reporttypes:'MarkdownSummaryGithub'

    - name: Write Coverage Badges to Job Summary
      run: |
        cat '![Line Coverage](${{ github.workspace }}/CodeCoverage/badge_linecoverage.svg)' >> $GITHUB_STEP_SUMMARY && \
        cat '![Branch Coverage](${{ github.workspace }}/CodeCoverage/badge_branchcoverage.svg) >> $GITHUB_STEP_SUMMARY && \
        cat '![Method Coverage](${{ github.workspace }}/CodeCoverage/badge_methodcoverage.svg) >> $GITHUB_STEP_SUMMARY

    - name: Write Coverage Summary to Job Summary
      run: cat ${{ github.workspace }}/CodeCoverage/SummaryGithub.md >> $GITHUB_STEP_SUMMARY
