name: 'Branch Build'
run-name: '${{ github.workflow }} for ${{ github.ref_name }}'

on: push

permissions:
  pull-requests: read
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '6.0.x', '7.0.x' ]
    steps:
    - name: Checkout
      uses: actions/checkout@v3  

    - name: Set Up .NET ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    
    - name: Configure Dependency Cache
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-nuget-${{ matrix.dotnet-version }}
        restore-keys: |
          ${{ runner.os }}-nuget-${{ matrix.dotnet-version }}

    - name: Restore ResultCs Dependencies
      run: dotnet restore ./src/ResultCs/ResultCs.csproj

    - name: Build ResultCs
      run: dotnet build ./src/ResultCs/ResultCs.csproj

    - name: Run ResultCs Unit Tests
      # run: dotnet test --logger trx --results-directory "TestResults-Unit-${{ matrix.dotnet-version }}" ./test/ResultCs.Tests.Unit/ResultCs.Tests.Unit.csproj
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput=./TestResults/lcov.info ./test/ResultCs.Tests.Unit/ResultCs.Tests.Unit.csproj
    
    - name: Upload Unit Test Results
      uses: actions/upload-artifact@v3
      with:
        name: dotnet-unit-test-results-${{ matrix.dotnet-version }}
        path: ./test/ResultCs.Tests.Unit/TestResults/lcov.info
      if: ${{ always() }}

    - name: Run ResultCs Integration Tests
      # run: dotnet test --logger trx --results-directory "TestResults-Integration-${{ matrix.dotnet-version }}" ./test/ResultCs.Tests.Integration/ResultCs.Tests.Integration.csproj
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput=./TestResults/lcov.info ./test/ResultCs.Tests.Integration/ResultCs.Tests.Integration.csproj

    - name: Create code coverage report
      run: |
        dotnet tool install -g dotnet-reportgenerator-globaltool
        reportgenerator -reports:$(Agent.WorkFolder)/**/lcov.info -targetdir:$(Build.SourcesDirectory)/CodeCoverage -reporttypes:'HTML;Badges'

    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: dotnet-test-results-${{ matrix.dotnet-version }}
        path: $(Build.SourcesDirectory)/CodeCoverage
      if: ${{ always() }}
