name: 'Run ${{ inputs.suite }} Tests'
description: 'Runs the specified testing suite and uploads the test ResultCs.'
inputs:
  suite:
    description: 'The test suite to run (e.g. Unit).'
    required: true
runs:
  - name: 'Run ResultCs ${{ inputs.suite }} Tests'
    run: dotnet test --logger trx --results-directory "TestResults-${{ inputs.suite }}-${{ matrix.dotnet-version }}" .test/ResultCs.Tests.${{ inputs.suite }}/ResultCs.Tests.${{ inputs.suite }}.csproj
  
  - name: Upload ${{ inputs.suite }} Test Results
    uses: actions/upload-artifact@v3
    with:
      name: dotnet-${{ inputs.suite }}-test-results-${{ matrix.dotnet-version }}
      path: TestResults-${{ inputs.suite }}-${{ matrix.dotnet-version }}
    if: ${{ always() }}